/*
 * generated by Xtext 2.14.0
 */
package at.ac.tuwien.big;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RovermlStandaloneSetup extends RovermlStandaloneSetupGenerated {

	public static void doSetup() {
		new RovermlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
