/*
 * generated by Xtext 2.14.0
 */
package at.ac.tuwien.big;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RovermlRuntimeModule extends AbstractRovermlRuntimeModule {
}
