grammar at.ac.tuwien.big.Roverml with org.eclipse.xtext.common.Terminals

import "http://www.big.tuwien.ac.at/roverml"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

RoverSystem returns RoverSystem:
	{RoverSystem}
	'roverSystem'
;

QualifiedName returns ecore::EString:
	ID (=> '.' ID)*;

EString returns ecore::EString:
	STRING | ID;

EFloat returns ecore::EFloat:
	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;

EInt returns ecore::EInt:
	'-'? INT;
