/*
 * generated by Xtext 2.14.0
 */
package at.ac.tuwien.big.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRovermlScopeProvider extends DelegatingScopeProvider {
}
