/*
 * generated by Xtext 2.14.0
 */
package at.ac.tuwien.big.ide;

import at.ac.tuwien.big.RovermlRuntimeModule;
import at.ac.tuwien.big.RovermlStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RovermlIdeSetup extends RovermlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RovermlRuntimeModule(), new RovermlIdeModule()));
	}
	
}
