/*
 * generated by Xtext 2.14.0
 */
package at.ac.tuwien.big.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RovermlAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("at/ac/tuwien/big/parser/antlr/internal/InternalRoverml.tokens");
	}
}
