/*
 * generated by Xtext 2.14.0
 */
package at.ac.tuwien.big.parser.antlr;

import at.ac.tuwien.big.parser.antlr.internal.InternalRovermlParser;
import at.ac.tuwien.big.services.RovermlGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RovermlParser extends AbstractAntlrParser {

	@Inject
	private RovermlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRovermlParser createParser(XtextTokenStream stream) {
		return new InternalRovermlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "NamedElement";
	}

	public RovermlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RovermlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
