/*
 * generated by Xtext 2.14.0
 */
package at.ac.tuwien.big.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RovermlUiModule extends AbstractRovermlUiModule {

	public RovermlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
